### ISSUE TITLE
 Planning for Section 2.1 (08/15)

### ISSUE THREAD

**Issue by kingcons** [kingcons/study-group#6] opened 2018-08-09 01:58 UTC
### Meeting Time

6pm at the Tourbuzz Offices on Wednesday, August the 15th.

### Group Leader of the Week

* TBD (Thanks again to @bigjust for leading section 1.3 :heart:)

This week is probably either me or @Christophin since @mlsimpson has been out with family stuff.

### The Planning Thread

We'll use this github issue as a discussion thread for:

* Suggesting topics or exercises we'd like to spend some time discussing in the next meeting
* Problems that should be *skipped*
* Questions about portions of the text or exercises
* Requests for pair programming (remote or otherwise)

Cheers, y'all! :metal: :beers: :computer:

**Comment by kingcons** [comment] 2018-08-10 13:42
I'll be taking point this week! Doing reading tonight, ask questions as you have them. :)

**Comment by Christophin** [comment] 2018-08-13 23:27
```
(define (gcd a b)
  (if (= b 0)
      a
      (gcd b (remainder a b))))

(define (Make-rat n d)
    (let ((g ((cond ((and (< n 0) (< d 0)) -)
                ((and (> n 0) (< d 0)) -)
                (else +))
                (gcd n d))))
        (cons (/ n g)
                  (/ d g))))
```

Here is my solution for 2.1

I feel like after looking at how gcd works, do we really need to care about checking n? n will only come back if b is zero, which would make n irrelevant since it will be divided by zero. (edit: this isn't true. I still think I'm onto something though) otherwise it will come back as some manipulated form of d. I think this can be reduced. Unless I'm missing something.

Thoughts?

**Comment by Christophin** [comment] 2018-08-13 23:51
Just went and smoked. I had it backwards. we will only get n back if d is zero. otherwise n will be a remainder, which, if you look at how gcd works, will be based off of (edit: d not b). Also, n will always be in the numerator spot so there is no need to check if it is syntactically correct.

**Comment by Christophin** [comment] 2018-08-14 00:50
After a bunch of tracing of gcd (which, if you want to trace, rename it to something else. gcd is build into racket and it won't let you override it and doesn't let you know that when you try.) and it seems like the one of the possible many problems is when gcd is evaluating, it will switch between negative and positive numbers. So it depends on how many times it's evaluated. Still that is based off d and shouldn't matter. the n is only important when deciding how to apply + or - to gcd. once it's in cons, who cares. it will always be right.

**Comment by Christophin** [comment] 2018-08-14 00:57
wait, right gcd only give us g, who cares what we do to n inside of it, it doesn't matter. I think I have something. (Edit: this is just a convoluted syntax problem involving g) all we care about is d. if g is negative it's d's fault.)

**Comment by Christophin** [comment] 2018-08-14 01:32
```
(define (Make-rat n d)
    (let ((g ((if (< d 0) - +) (abs (gcd n d)))))
        (cons (/ n g)
              (/ d g))))
```

This appears to work.

**Comment by Christophin** [comment] 2018-08-14 01:50
We should talk about this on Wednesday, There is a piece I'm not sure I'm understanding here. (edit: never mind I think I got it.

**Comment by kingcons** [comment] 2018-08-14 02:23
It's an impressively concise solution and relatively clear, I'm just not sure I worked out the GCD signedness stuff enough to be confident I fully understand it. I.e. I don't quite follow the path you used to arrive at this answer. :)

Have been thinking about this while working on emulator stuff of late. There's no such thing as code being "readable" in some sense, not only because being readable implies assumptions about the context of the reader but also because code doesn't present a linear narrative! (see also: [peter seibel][code-is-not-literature] and [stephen malina][nobody-reads-code], though [luke gorrie][lukego] may be a counterpoint.)

[lukego]: http://lukego.github.io/blog/2012/10/24/readable-programs/
[code-is-not-literature]: http://www.gigamonkeys.com/code-reading/
[nobody-reads-code]: http://akkartik.name/post/comprehension

Still, code style *matters*. Documentation and tests are also important for being able to re-establish the _provenance_ of a piece of code, both the problem it solved and the path to the solution. I continue to want to find a way _explain code_ without relying on fairly static tools like documentation, the code itself, or even tests. Legacy code and software preservation only makes this need more obvious.

My primary motivation in the emulator is in finding ways to generate an _explanation_ of the binaries it runs _without_ resorting to just trying to reverse engineer something close to original source code. It's the intent and constraints that matter, not necessarily the solution the developers wound up with. It seems to me that _tracing execution dynamically_ and finding reasonable ways to present that at different levels of abstraction might offer a way out. Ugh, I should really turn this into a blog post. 😪 

Also, sorry I think I derailed this thread with a bunch of stuff in my head but it isn't SICP? 😞

**Comment by Christophin** [comment] 2018-08-14 16:55
Let's talk about it on Wednesday. I basically used this thread as a rubber duck and didn't circle back and explain all my conclusions.

**Comment by Christophin** [comment] 2018-08-16 04:59
@kingcons hey dude please don't close this issue. I'm too tired to explain now but I've got some more things to say. Open a new issue for the next session but please leave this one open for further conversation about today's meeting.

**Comment by kingcons** [comment] 2018-08-16 14:21
Yeah man, no problem. I'm gonna go ahead and move on to 2.2 for next week. Will probably open a thread on it later today.

For @bigjust: I skipped the following problems -> 2.3, 2.6, 2.11, 2.13, 2.15, 2.16
I also think my answers were wrong or not complete for: 2.8, 2.9

**Comment by Christophin** [comment] 2018-08-16 18:46
Alright so this shit is pissing me off. [Here](http://www.billthelizard.com/2010/09/sicp-21-rational-numbers.html) [are](https://github.com/sarabander/p2pu-sicp/blob/master/2.1/2.01.scm) [some](https://github.com/qiao/sicp-solutions/blob/master/chapter2/2.01.scm) [solutions](https://wizardbook.wordpress.com/2010/11/30/exercise-2-1/) [I've](https://github.com/Liutos/SICP-solutions/blob/master/ch2/2.1.scm) [found.](https://github.com/phoeninee/SICP-solutions/blob/master/Chapter%202-Building%20Abstractions%20with%20Data/1.Introduction%20to%20Data%20Abstraction/2.01.rkt) At the bottom of [this](https://github.com/cdelahousse/Structure-and-Interpretation-of-Computer-Programs--SICP--Solutions/blob/master/2.1.scm) solution you can see my answer that they claim they got from the 'scheme wiki'. I think they are talking about this [dead](http://community.schemewiki.org/?SICP-Solutions) website which we can use wayback machine to see [here](https://web.archive.org/web/20180211174128/http://community.schemewiki.org:80/?sicp-ex-2.1). But this just comes to the same conclusion I did and doesn't go any farther. the wayback machine comments also lead me to [this](https://web.archive.org/web/20091214225643/http://sicp.org.ua:80/sicp/Exercise2-1) which also did not provide any insight.

WHY CAN'T I FIND SOMEONE WHO APPROACHED THIS PROBLEM USING THE USE CASES THE QUESTION LITERALLY LAID OUT LIKE THE MAJORITY OF MY STUDY GROUP DID? Have you guys just known each other so long you think alike and are just wrong in this case? Have you been paid developers for so long that this question was just a simple 'ticket' for you guys and you didn't approach it like a student would? Has google scraped and fucked with the internet to such an extent that it's only showing me what I was to see? (only being a little flippant here) 

WHAT IS HAPPENING?? I know the problem isn't particularly difficult so it might seem dumb that I'm stuck on this but it's more the ramifications of our different solutions that has me questioning.

I still don't know how I feel about this black box idea.

And all that doesn't even go into the readability thing @kingcons brought up. I don't even know what the fuck that means any more. Which, of all our solutions, and the ones I've found, is the most readable? I don't know how to even begin to answer that question.

Also fuck you Brit for dumping all that shit on me last night (also :heart: though, really!) I'm having trouble thinking about anything else but that and I don't know anywhere near enough to address it. 
Has it been proven to be impossible like Kayla said? Were we, as programmers, ever on a path that lead to your vision? If so, when did we veer away? We talked about the people who only care about money ripping this thing of ours away from us. Is there more nuance than that? Was this ever addressed in the early days of programming? If not, why not? It's such an obvious and important thing. At least after speaking to you it is.  I'm going to go cathartically bust your balls on TIY slack now.

**Closed as completed** 2018-08-22 20:53 UTC
